# Generated by Django 4.2.1 on 2023-06-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0004_notas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariocolegio",
            name="password",
            field=models.CharField(default="123", max_length=10),
        ),
    ]
